import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/theme-provider';
import { Navbar } from '@/components/navbar';
import { Toaster } from '@/components/ui/sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SendFilesPro - Free & Secure Unlimited File Sharing',
  description: 'Send files of unlimited size between computers for free with SendFilesPro. Enjoy enterprise-level security, end-to-end encryption, and instant sharing with no registration required.',
  keywords: [
    'file sharing',
    'secure file transfer',
    'unlimited file size sharing',
    'free file sharing',
    'send files online',
    'end-to-end encryption',
    'file upload service',
    'fast file transfer',
    'free file transfer',
    'large file sharing',
    'private file transfer',
    'share files securely',
    'online file transfer',
    'no registration file sharing',
    'anonymous file sharing',
    'secure file upload',
    'file sharing for businesses',
    'send large files',
    'send files free',
    'best file sharing service',
    'secure file transfer service',
    'large file upload',
    'fast file upload',
    'file sharing for teams',
    'file sharing app',
    'instant file sharing',
    'encrypted file sharing',
    'share files without registration',
    'free file storage',
    'free file sharing for businesses',
    'cloud file sharing',
    'safe file transfer',
    'free file transfer service',
    'end-to-end encrypted file sharing',
    'private file sharing',
    'free file transfer website',
    'secure cloud storage',
    'transfer large files free',
    'send files encrypted',
    'share documents securely',
    'file sending platform',
    'file sharing website',
    'instant file transfer',
    'quick file sharing',
    'file sharing without limits',
    'send documents securely',
    'free unlimited file transfer',
    'secure file sharing app',
    'online file sharing service',
    'easy file sharing',
    'transfer files securely',
    'secure document transfer',
    'free file upload',
    'free cloud file sharing',
    'private cloud file sharing',
    'simple file sharing',
    'encrypted file upload',
    'share big files',
    'transfer large files without registration',
    'free file sending',
    'no registration file transfer',
    'online file sending',
    'fast file sending',
    'safe file upload',
    'file sharing platform',
    'file transfer website',
    'private file transfer service',
    'share files for free',
    'large file sending',
    'share files instantly',
    'file sharing solution',
    'file transfer service without registration',
    'unlimited file sharing free',
    'secure file sharing platform',
    'file sharing without email',
    'share files with anyone',
    'online file transfer service',
    'secure online file sharing',
    'transfer files easily',
    'free file sharing platform',
    'send files fast',
    'encrypted document transfer',
    'file sharing encryption',
    'large file transfer',
    'encrypted file sharing service',
    'unlimited file upload',
    'file sharing with end-to-end encryption',
    'safe file transfer online',
    'no signup file transfer',
    'easy file sharing platform',
    'free document sharing',
    'send files anonymously',
    'share large files with encryption',
    'send files from PC to PC',
    'secure file sharing tool',
    'quick document sharing',
    'free file exchange',
    'file sharing without limits',
    'cloud file upload',
    'private file sharing platform',
    'send files through the cloud',
    'share files from PC to PC',
    'cloud-based file sharing',
    'secure file sharing for business',
    'transfer files with no size limits',
    'transfer files privately',
    'safe document sharing',
    'private file upload',
    'secure file sending',
    'free encrypted file sharing',
    'file sharing for private use',
    'free encrypted file transfer',
    'document sharing without limits',
    'send files securely online',
    'free file storage service',
    'secure sharing platform',
    'file upload without registration',
    'share big documents securely',
    'encrypted file sharing online',
    'file sharing no sign up required',
    'best file transfer platform',
    'send files easily',
    'secure large file upload',
    'file sharing free no signup',
    'secure file sharing tool',
    'instant file transfer service',
    'transfer files to anyone',
    'secure cloud file transfer',
    'best free file transfer tool',
    'simple file upload',
    'send files with encryption',
    'transfer large files instantly',
    'encrypted transfer service',
    'free file sharing no sign-up',
    'large document sharing platform',
    'easy file transfer online',
    'send files from anywhere',
    'transfer files with no hassle',
    'free file transfer without registration',
    'encrypted file exchange',
    'transfer big files free',
    'secure transfer files online',
    'best secure file transfer',
    'no registration file upload',
    'free upload for large files',
    'transfer files securely free',
    'share documents with encryption',
    'free transfer service',
    'upload and share files securely',
    'safe upload service',
    'easy file transfer no registration',
    'file upload without limits',
    'large file sharing no registration',
    'free cloud-based transfer',
    'free secure file sending',
    'upload files securely',
    'fast and secure file transfer',
    'fast and easy file upload',
    'secure file sharing without sign up',
    'file transfer with encryption',
    'send files with no size limit',
    'file sharing no email required',
    'upload files with encryption',
    'transfer files from any device',
    'encrypted upload service',
    'best file sharing app free',
    'transfer large files securely',
    'private file transfer service',
    'file sharing with no account',
    'share files to cloud',
    'instant file sharing service',
    'secure file sending platform',
    'send files without hassle',
    'share files in seconds',
    'encrypted document sharing',
    'private file transfer app',
    'file sending platform for businesses',
    'share files without limits',
    'fast cloud file sharing',
    'easy document transfer',
    'file sharing with no email',
    'free encrypted document sharing',
    'best file upload service',
    'secure file exchange tool',
    'send files with no size limits',
    'large file transfer service',
    'file sharing across devices',
    'free file sharing app',
    'send documents with encryption',
    'large file upload for free',
    'file transfer free online',
    'share files quickly and securely',
    'free file exchange service',
    'encrypted file upload tool',
    'send files with no signup',
    'easy encrypted file transfer',
    'no registration file sharing service',
    'best free file sharing platform',
    'send files securely free',
    'free and secure file transfer',
    'fast file upload service',
    'send files instantly for free',
    'no size limit file sharing',
    'upload large files for free',
    'cloud-based file transfer',
    'free file sharing website',
    'secure file sharing with no signup',
    'send files safely',
    'encrypted upload tool',
    'cloud-based file transfer service',
    'share files with encryption online',
    'transfer files anonymously',
    'secure file sharing solution',
    'share files without creating an account',
    'large document transfer',
    'no sign up required file sharing',
    'transfer encrypted files free',
    'upload files without email',
    'free cloud transfer service',
    'quick file upload',
    'free file sharing tool',
    'large file transfer free',
    'share files to anyone without limits',
    'fast secure file sharing',
    'file sharing tool for businesses',
    'send documents for free',
    'share files with no limits free',
    'private file upload service',
    'transfer files anonymously online',
    'secure file exchange platform',
    'quick file sending online',
    'share encrypted files online',
    'send large files securely free',
    'transfer files without email',
    'no limit file sharing online',
    'free large file transfer tool',
    'fast secure file upload',
    'best file sharing services online',
    'free encrypted file transfer service',
    'send files via cloud',
    'file sharing with no registration required',
    'transfer files securely no signup',
    'send documents securely online',
    'file sharing with encryption tool',
    'send encrypted files for free',
    'free file sharing for team collaboration',
    'file transfer tool with no limits',
    'secure file sharing without email',
    'share files easily online',
    'large file sending without registration',
    'cloud file upload service',
    'secure file sharing solution for businesses',
    'send files with ease',
    'secure file exchange without limits',
    'free encrypted file sharing tool',
    'send files with no account required',
    'upload encrypted files securely',
    'cloud-based file upload',
    'transfer files with full encryption',
    'quick and secure file sharing',
    'share files across platforms',
    'free file sharing no email',
    'send files with no hassle free',
    'fast file upload for large files',
    'send encrypted documents online',
    'file transfer solution with encryption',
    'transfer large documents securely',
    'share documents without registration',
    'send files through cloud storage',
    'secure and fast file transfer',
    'free and secure file sharing tool',
    'cloud storage file sharing',
    'transfer files with encryption online',
    'upload files securely online',
    'fast file transfer with encryption',
    'large file sharing service',
    'private file upload without registration',
    'send documents without limits',
    'share files with large size limits',
  ],
  authors: [{ name: 'SendFilesPro Team' }],
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://sendfilespro.us.kg',
    title: 'SendFilesPro - Free & Secure Unlimited File Sharing',
    description: 'Send files of unlimited size between computers for free. No registration required, with full end-to-end encryption.',
    siteName: 'SendFilesPro',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'SendFilesPro - Free & Secure Unlimited File Sharing',
    description: 'Instantly share files of any size for free, with top-notch security and encryption. Try it today!',
  },
  robots: {
    index: true,
    follow: true,
  },
  manifest: '/manifest.json',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  metadataBase: new URL('https://sendfilespro.us.kg'),  // <-- Add this line
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main id="main-content" role="main">
            {children}
          </main>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
